export const COLOR_MODE_KEY = 'color-mode'
export const INITIAL_COLOR_MODE_CSS_PROP = '--initial-color-mode'
export const DICTIONARY_API_URL =
  'https://api.dictionaryapi.dev/api/v2/entries/en/'
export const WORD = 'word'
export const TEXT = 'text'
export const AUDIO = 'audio'
export const MEANINGS = 'meanings'
export const PART_OF_SPEECH = 'partOfSpeech'
export const SYNONYMS = 'synonyms'
export const DEFINITION = 'definition'
export const DEFINITIONS = 'definitions'
export const SOURCE_URL = 'sourceUrl'
export const EXAMPLE = 'example'
